/* generated By ./config/generate.js
* Mon Aug 27 2018 13:12:56 GMT+0800 (中国标准时间)
*/

module.exports.attr = require('./attr/attr.js');
module.exports.removeAttr = require('./attr/removeAttr.js');
module.exports.addClass = require('./class/addClass.js');
module.exports.class = require('./class/class.js');
module.exports.hasClass = require('./class/hasClass.js');
module.exports.removeClass = require('./class/removeClass.js');
module.exports.toggleClass = require('./class/toggleClass.js');
